version: "2"
services:
  node:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - statsd
    environment:
      GRAPHITE_PORT_8125_UDP_ADDR: "statsd"
    env_file: docker-compose.env
  statsd:
    image: ennexa/statsd
    links: 
     - graphite
    volumes:
     - /data/log/elasticsearch:/etc/statsd
  graphite: 
    image: ennexa/graphite
    restart: always
    volumes:
     - /data/log/graphite:/opt/graphite/conf
     - /data/data/whisper:/opt/graphite/storage/whisper
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
     - /data/data/grafana:/var/lib/grafana
    links:
     - graphite
    ports:
     - "1337:3000"
