version: "2"
services:
  node:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - statsd
    environment:
      GRAPHITE_PORT_8125_UDP_ADDR: "statsd"
    env_file: docker-compose.env
    ports:
     - "443:443"
     - "80:80"
  statsd:
    image: ennexa/statsd
    links: 
     - graphite
  graphite: 
    image: ennexa/graphite
    restart: always
    volumes:
     - /data/data/whisper:/opt/graphite/storage/whisper
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
     - /data/data/grafana:/var/lib/grafana
    links:
     - graphite
    ports:
     - "1337:3000"
