
- name: Check for data volume
  stat: path=/dev/xvdf
  register: data_volume

- name: Create fs on data volume
  filesystem: fstype=ext4 dev=/dev/xvdf
  when: data_volume.stat.exists

- name: Mount data volume
  mount: name=/data src=/dev/xvdf fstype=ext4 state=present
  when: data_volume.stat.exists

- name: Create data subdirectories
  file: state=directory recurse=true path={{ item }} mode=777
  when: data_volume.stat.exists
  with_items:
  - /data/data/whisper
  - /data/data/elasticsearch
  - /data/data/grafana
  - /data/log/graphite
  - /data/log/elasticsearch

- name: Set docker volume options
  set_fact:
    docker_volume_options:
    - /data/data/whisper:/opt/graphite/storage/whisper
    - /data/data/elasticsearch:/var/lib/elasticsearch
    - /data/data/grafana:/opt/grafana/data
  when: data_volume.stat.exists